export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9f7 0%, #fcf0c7 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #d4ecff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #ffe4d4 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #e7f6fe 0%, #d4f0fa 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #ffe0f7 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8fef3 0%, #c8f7e8 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #ddd7f8 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fadede 100%)' },
];

export const API_FEATURES = [
  {
    id: '01',
    title: 'Tailored Just for You',
    description:
      'Get interview questions and model answers based on your role, experience and specific focus areas - no generic practice here.',
  },
  {
    id: '02',
    title: 'Learn at Your Own Pace',
    description:
      'Expand answers only when you are ready. Deep diver into any concept instantly with AI-powered detailed explanation.',
  },
  {
    id: '03',
    title: 'Capture Your Insights',
    description:
      'Add personal notes to any questions and pin important ones to the top — making your learning more organized and impactful.',
  },
  {
    id: '04',
    title: 'Understand the "Why" Behind Answers',
    description:
      'Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.',
  },
  {
    id: '05',
    title: 'Save, Organize and Revisit',
    description:
      'Easily save your interview sets, organize them neatly in your dashboard and pick up your preparation right where you left off.',
  },
];
