const { GoogleGenAI } = require('@google/genai');
const {
  conceptExplainPrompt,
  questionAnswerPrompt,
} = require('../utils/prompts');

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// @desc    Generate interview questions and answers using gemini
// @route   POST /api/ai/generate-questions
// @access  Private
const generateInterviewQuestions = async (req, res) => {
  try {
    const { role, experience, topicsToFocus, numberOfQuestions } = req.body;

    if (!role || !experience || !topicsToFocus || !numberOfQuestions) {
      return res.status(400).json({ message: 'Missing required fields' });
    }

    const prompt = questionAnswerPrompt(
      role,
      experience,
      topicsToFocus,
      numberOfQuestions
    );

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash-lite',
      contents: prompt,
    });

    const result = response.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!result) {
      throw new Error('No content generated by Gemini');
    }

    let rawText = result;

    // Clean it: Remove ```json and ``` from beginning and end
    // Clean common Gemini formatting issues
    const cleaned = rawText
      .replace(/```json/g, '')
      .replace(/```/g, '')
      .trim();

    let data;
    try {
      data = JSON.parse(cleaned);
    } catch (e) {
      return res.status(500).json({
        message: 'Invalid JSON returned by AI',
        raw: cleaned,
      });
    }

    res.status(200).json(data);
  } catch (error) {
    res
      .status(500)
      .json({ message: ' Failed to generate questions', error: error.message });
  }
};

// @desc    Generates explains a interview questions
// @route   /api/ai/generate-explanation
// @access  Private
const generateConceptExplanation = async (req, res) => {
  try {
    const { question } = req.body;

    if (!question) {
      return res.status(404).json({ message: 'Missing required fields' });
    }

    const prompt = conceptExplainPrompt(question);

    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash-lite',
      contents: prompt,
    });

    let rawText = response.text;

    // Clean it: Remove ```json and ```from beginning and end
    const cleanedText = rawText
      .replace(/^```json\s*/, '') //remove starting ```json
      .replace(/```$/, '') // remove ending ```
      .trim(); // remove extra spaces

    // Now safe to parse
    const data = JSON.parse(cleanedText);

    res.status(200).json(data);
  } catch (error) {
    res.status(500).json({
      message: ' Failed to generate explanations',
      error: error.message,
    });
  }
};

module.exports = { generateInterviewQuestions, generateConceptExplanation };
